git add Barndance_01.mp3
git add Bring_Me_Little_Water_Sylvie_\(01\).mp3
git add Bring_Me_Little_Water_Sylvie___Parts.mp3
git add Burning_Of_Auchindon___In_The_Crypt.mp3
git add Cloud_Song___Glee_07.mp3
git add Dark_As_A_Dungeon___In_The_Crypt.mp3
git add Deep_Blue_Sea___Postcamps_07.mp3
git add Deep_Down_In_My_Soul___In_The_Crypt.mp3
mv	Dona_Nobis_Parcem_\(Ffs\).mp3 Dona_Nobis_Parcem_\(FFS\).mp3
mv	Fathom_The_Bowl_\(Ffs\).mp3 Fathom_The_Bowl_\(FFS\).mp3
mv	Fiddler\'s_Green_\(Ffs\).mp3 Fiddler\'s_Green_\(FFS\).mp3
mv	Fiddlers_Green.mp3 Fiddler\'s_Green.mp3
git add Go_Down_You_Blood_Red_Roses___In_The_Crypt.mp3
git add Goodnight_Irene___In_The_Crypt.mp3
mv	I\'Ll_Fly_Away.mp3	I\'ll_Fly_Away.mp3
mv	I\'M_Gonna_Be_An_Engineer_\(Peggy_Seeger\).mp3 I\'m_Gonna_Be_An_Engineer_\(Peggy_Seeger\).mp3
mv	I_Wonder_If_I\'M_Growing.mp3 I_Wonder_If_I\'m_Growing.mp3
mv	It_Ain\'t_Me_You\'Re_Looking_For.mp3 It_Ain\'t_Me_You\'re_Looking_For.mp3
mv	Lowlands_\(Ffs\).mp3 Lowlands_\(FFS\).mp3
git add Mallezway___Postcamps_07.mp3
mv Mary_Ellen_Carter__Ffs.mp3 Mary_Ellen_Carter__FFS.mp3
git add Mathilda___Theo_Bard.mp3
git add Moonganga___In_The_Crypt.mp3
git add Oak_And_Ash_And_Thorn_Round___Stable_Singers.mp3
git add Oh_Lord_Won\'t_You_Buy_Me_A_Mercedes_Benz_\(01\).mp3
git add Oh_Lord_Won\'t_You_Buy_Me_A_Mercedes_Benz_\(02\).mp3
mv	Oh_You\'Ll_Never_Get_To_Heaven.mp3 Oh_You\'ll_Never_Get_To_Heaven.mp3
mv OldJoeClark.html Old_Joe_Clark.html
git add Old_Virginia.mp3
git add Orlando\'s_Pigs___Stable_Singers.mp3
git add	Paddy_Doyles_Boots___In_The_Crypt.mp3
git add Paddy_West___Stable_Singers.mp3
git add Poor_Wayfaring_Stranger___Nancy_And_Amy.mp3
git add Praise_His_Holy_Name___In_The_Crypt.mp3
git add Sally_Free_And_Easy.mp3
git add Sam_Lee\'s_Hello_Little_Stream___Stable_Singers.mp3
git add Shtomni_Omni___In_The_Crypt.mp3
git add Silver_Dagger___Jaunty_Ukelele.mp3
git add Sixteen_Tons__Bellair_Remix.mp3
git add	Siyahamba___In_The_Crypt.mp3
git add Tu_We_\+_Hill_And_Gully_Rider___Postcamps_07.mp3
git add Um_A_Lay___Glee_07.mp3
git add Um_A_Lay___Wangs.mp3
git add Umkhonto_We_Sizwe___In_The_Crypt.mp3
git add Wade_In_The_Water___Postcamps_07.mp3
git add We\'ve_Got_All_The_Love___Parts.mp3
git add Went_Down_To_The_River_To_Pray.mp3
mv Whisky_On_A_Sunday_\(Ffs\).mp3 Whisky_On_A_Sunday_\(FFS\).mp3
mv	White_Cockade_\(Barnyard\).mp3 White_Cockade__Barnyard.mp3
git add Yolomano___In_The_Crypt.mp3
