mv Oh_Lord_Won\'t_You_Buy_me_A_Mercedes_Benz_\(02\).mp3 Oh_Lord_Won\'t_You_Buy_Me_A_Mercedes_Benz_\(02\).mp3
mv We\'re_Coming_Home_\(Rain_Soaked_Hippies\).mp3 We\'Re_Coming_Home_\(Rain_Soaked_Hippies\).mp3
mv Fiddler\'S_Green_09.mp3 Fiddler\'s_Green_09.mp3
mv Oh_You\'ll_Never_Get_To_Heaven.mp3 Oh_You\'Ll_Never_Get_To_Heaven.mp3
mv We\'ve_Got_All_The_Love.mp3 We\'Ve_Got_All_The_Love.mp3
mv Sam_Lee\'S_Hello_Little_Stream___Stable_Singers.mp3 Sam_Lee\'s_Hello_Little_Stream___Stable_Singers.mp3
mv Fiddler\'S_Green.mp3 Fiddler\'s_Green.mp3
mv I\'m_Gonna_Be_An_Engineer_\(Peggy_Seeger\).mp3 I\'M_Gonna_Be_An_Engineer_\(Peggy_Seeger\).mp3
mv Paddy_Doyle\'S_Boots.mp3 Paddy_Doyle\'s_Boots.mp3
mv I\'ll_Fly_Away.mp3 I\'Ll_Fly_Away.mp3
mv It_Ain\'T_Me_You\'Re_Looking_For.mp3 It_Ain\'t_Me_You\'Re_Looking_For.mp3
mv There_Ain\'T_No_Flies_On_Us.mp3 There_Ain\'t_No_Flies_On_Us.mp3
mv We\'re_Healing_The_World_\(Rain_Soaked_Hippies\).mp3 We\'Re_Healing_The_World_\(Rain_Soaked_Hippies\).mp3
mv I_Wonder_If_I\'m_Growing.mp3 I_Wonder_If_I\'M_Growing.mp3
mv We\'ve_Got_All_The_Love_\(parts\).mp3 We\'Ve_Got_All_The_Love_\(Parts\).mp3
mv My_Sweet_Love_Ain\'T_Around.mp3 My_Sweet_Love_Ain\'t_Around.mp3
mv Derby_Ram\'S_Tail.mp3 Derby_Ram\'s_Tail.mp3
mv Fiddler\'s_Green_\(FFS\).mp3 Fiddler\'s_Green_\(Ffs\).mp3
mv Oh_Lord_Won\'t_You_Buy_me_A_Mercedes_Benz_\(01\).mp3 Oh_Lord_Won\'t_You_Buy_Me_A_Mercedes_Benz_\(01\).mp3
mv Don\'T_Let_It_Bother_You.mp3 Don\'t_Let_It_Bother_You.mp3
mv Reuben\'S_Train.mp3 Reuben\'s_Train.mp3
mv Orlando\'S_Pigs___Stable_Singers.mp3 Orlando\'s_Pigs___Stable_Singers.mp3
mv Ain\'T_No_Sunshine_When_She\'S_Gone.mp3 Ain\'t_No_Sunshine_When_She\'s_Gone.mp3
mv No_Man\'S_Land.mp3 No_Man\'s_Land.mp3
mv It_Ain\'t_Me_You\'re_Looking_For.mp3 It_Ain\'t_Me_You\'Re_Looking_For.mp3
mv Mary_Don\'T_You_Weep.mp3 Mary_Don\'t_You_Weep.mp3
mv Grandma\'S_Hands.mp3 Grandma\'s_Hands.mp3
mv Don\'T_You_Hear_Jerusalem_Mourn.mp3 Don\'t_You_Hear_Jerusalem_Mourn.mp3
