name: Run python jinja and commit

on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: List all files
      run: cd mp3; ls *.mp3 > ../all.txt

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install Jinja2 tinytag 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: execute python script for All_Songs
      run: |
        python jinja_site.py All_Songs.txt
    - name: execute python script for selection
      run: |
        python jinja_site.py selection.txt
    - name: execute python script for Songbook_2017
      run: |
        python jinja_site.py Songbook_2017.txt
    - name: execute python script for Songbook_2012
      run: |
        python jinja_site.py Songbook_2012.txt

    - name: Make Songbook_2017 the default
      run: |
        cp Songbook_2017.html index.html


    - name: Commit generated files
      run: 

        git config --local user.email "timp@paneris.org"
      
        git config --global user.name "TimP Github"
        
        git commit -m "Github Action jinja.yml - $(date)" -a

    - name: Push generated files
      uses: ad-m/github-push-action@v0.8.0
      with:
          branch: gh-pages #ignore if your branch is master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
