name: Run PHP and commit

on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: Validate composer.json and composer.lock
    #  run: composer validate --strict

#    - name: Cache Composer packages
#      id: composer-cache
#      uses: actions/cache@v3
#      with:
#        path: vendor
#        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-php-

    - name: Run the build php script
      run: php jukebox.php > index.html

    - name: Commit generated files
      run: 

        git config --local user.email "timp@paneris.org"
      
        git config --global user.name "TimP Github"
  
        git commit -m "Github Actions $(date)" index.html 
        
    - name: Push generated files
      uses: ad-m/github-push-action@v0.8.0
      with:
          branch: gh-pages #ignore if your branch is master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
