name: Run PHP and commit

on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install php-getid3
      run: sudo apt-get install -y php-getid3
    
    - name: List all files
      run: ls *.mp3 > index.txt

    - name: Run the build script for all files
      run: php jukebox.php index.txt > index.html

    - name: Run the build script for Tim's Selection
      run: php jukebox.php tim.txt > tim.html

    - name: Commit generated files
      run: 

        git config --local user.email "timp@paneris.org"
      
        git config --global user.name "TimP Github"
  
        git commit -m "Github Actions $(date)" index.html 
        
    - name: Push generated files
      uses: ad-m/github-push-action@v0.8.0
      with:
          branch: gh-pages #ignore if your branch is master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
